# Generated by Django 4.2.7 on 2023-11-13 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('street_numbre', models.IntegerField()),
                ('adrees', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
